import type { Category } from '@/types';

/** Common brands — users can still type anything not listed. */
export const BRAND_SUGGESTIONS: readonly string[] = [
  'Apple',
  'Samsung',
  'Google',
  'Xiaomi',
  'Redmi',
  'OnePlus',
  'Tecno',
  'Infinix',
  'Itel',
  'Huawei',
  'Oppo',
  'Vivo',
  'Realme',
  'Nokia',
  'Motorola',
  'Sony',
  'Nothing',
  'Fairphone',
  'Honor',
  'Poco',
  'LG',
  'Microsoft',
  'HP',
  'Dell',
  'Lenovo',
  'ASUS',
  'Acer',
  'MSI',
  'Razer',
].sort((a, b) => a.localeCompare(b));

const PHONE_MODELS: readonly string[] = [
  'iPhone 16 Pro Max',
  'iPhone 16 Pro',
  'iPhone 16 Plus',
  'iPhone 16',
  'iPhone 15 Pro Max',
  'iPhone 15 Pro',
  'iPhone 15 Plus',
  'iPhone 15',
  'iPhone 14 Pro Max',
  'iPhone 14 Pro',
  'iPhone 14 Plus',
  'iPhone 14',
  'iPhone 13 Pro Max',
  'iPhone 13 Pro',
  'iPhone 13 mini',
  'iPhone 13',
  'iPhone SE (3rd generation)',
  'Samsung Galaxy S24 Ultra',
  'Samsung Galaxy S24+',
  'Samsung Galaxy S24',
  'Samsung Galaxy S23 Ultra',
  'Samsung Galaxy S23+',
  'Samsung Galaxy S23',
  'Samsung Galaxy A55',
  'Samsung Galaxy A35',
  'Samsung Galaxy A25',
  'Samsung Galaxy Z Fold 6',
  'Samsung Galaxy Z Flip 6',
  'Google Pixel 9 Pro XL',
  'Google Pixel 9 Pro',
  'Google Pixel 9',
  'Google Pixel 8 Pro',
  'Google Pixel 8',
  'Google Pixel 8a',
  'Xiaomi 14 Ultra',
  'Xiaomi 14',
  'Redmi Note 13 Pro',
  'Redmi Note 13',
  'OnePlus 12',
  'OnePlus 12R',
  'OnePlus Nord 4',
  'Tecno Phantom V Fold',
  'Tecno Camon 30 Premier',
  'Tecno Camon 30',
  'Infinix Note 40 Pro',
  'Infinix Note 40',
  'Infinix Zero 40',
];

const TABLET_MODELS: readonly string[] = [
  'iPad Pro 13" (M4)',
  'iPad Pro 11" (M4)',
  'iPad Air 13" (M2)',
  'iPad Air 11" (M2)',
  'iPad (10th generation)',
  'iPad mini (6th generation)',
  'Samsung Galaxy Tab S9 Ultra',
  'Samsung Galaxy Tab S9+',
  'Samsung Galaxy Tab S9',
  'Samsung Galaxy Tab A9+',
  'Xiaomi Pad 6 Pro',
  'Lenovo Tab P12',
  'Microsoft Surface Pro 11',
];

/** Models shown in the name combobox for phones / tablets; other categories use a plain text name. */
export function suggestedNamesForCategory(category: Category): readonly string[] {
  if (category === 'phones') return PHONE_MODELS;
  if (category === 'tablets') return TABLET_MODELS;
  return [];
}
